baseURL = "/"
languageCode = 'en-us'
title = "OpenLvVision"

[module]
    [[module.imports]]
        path = "lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs]
	darkMode = true
	title = "OpenLvVision"
	sidebarIcons = true
	titleIcon = true

[params.social]
	github = "OpenLvVision"

[params.footer]
	copyright = "© Lukas Kamleitner. All rights reserved."

[menu]
[[menu.primary]]
    name  = "Docs"
    url = "docs/"
    identifier = "docs"
    weight = 1