baseURL = "https://www.openlvvision.org/"
languageCode = 'en-us'
title = "OpenLvVision"

[module]
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]
     Description = "The personal website, blog and dev diary of clairecodes"

[params.docs]
	darkMode = true
	title = "OpenLvVision"
	sidebarIcons = true
	titleIcon = false

[params.social]
	github = "OpenLvVision"

[params.footer]
	copyright = "© Lukas Kamleitner. All rights reserved."
