baseURL = "https://www.openlvvision.org/"
languageCode = 'en-us'
title = "OpenLvVision"

[module]
    [[module.imports]]
        path = "lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs]
	darkMode = true
	title = "OpenLvVision"
	sidebarIcons = true
	titleIcon = true

[params.social]
	github = "OpenLvVision"

[params.footer]
	copyright = "© Lukas Kamleitner. All rights reserved."

[menu]
[[menu.primary]]
    name  = "Installation"
    url = "docs/installation/"
    identifier = "Installation"
    weight = 1
[[menu.primary]]
    name  = "Documentation"
    url = "docs/"
    identifier = "Documentation"
    weight = 2
[[menu.primary]]
    name  = "VIPM"
    url = "https://www.vipm.io/publisher/openlvvision/"
    identifier = "VIPM"
    weight = 3